language: python
python:
  - "3.5"
before_install:
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - sleep 3
install:
  - pip install -r requirements.txt
before_script:
  - python manage.py migrate
script:
  - python manage.py test