language: python
python:
  - "3.5"
before_install:
  - "wget https://www.ebi.ac.uk/~luciani/Oracle/oracle.zip && unzip oracle.zip -d oracle"
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "export ORACLE_HOME=$(pwd)/oracle/"
  - "export LD_LIBRARY_PATH=$(pwd)/oracle/"
  - "export DYLD_LIBRARY_PATH=$(pwd)/oracle/"
  - sleep 3
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.1.deb && sudo dpkg -i --force-confnew elasticsearch-5.1.1.deb && sudo service elasticsearch restart
services:
  - elasticsearch
install:
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt
before_script:
  - sleep 10
  - curl -XPUT 'localhost:9200/test?pretty' -d @config/elastic_mapping.json
script:
  - coverage run --source='.' manage.py test
after_success:
  coveralls
branches:
  only:
    - master
    - new_datawarehouse
    - elastic_exploration
