sudo: required
dist: trusty
language: python
python:
  - "3.5"
addons:
  chrome: stable
before_cache:  - "rm -f $HOME/selenium/geckodriver-v0.11.1-linux32.tar.gz"

before_install:
  - jdk_switcher use oraclejdk8
  - "wget https://www.ebi.ac.uk/~luciani/Oracle/oracle.zip && unzip oracle.zip -d oracle"
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "export ORACLE_HOME=$(pwd)/oracle/"
  - "export LD_LIBRARY_PATH=$(pwd)/oracle/"
  - "export DYLD_LIBRARY_PATH=$(pwd)/oracle/"
  - "export BROWSER_TEST=chrome"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - sleep 3
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.1.deb && sudo dpkg -i --force-confnew elasticsearch-5.1.1.deb && sudo service elasticsearch restart
services:
  - elasticsearch
install:
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt
before_script:
  - sleep 10
  - curl -XPUT 'localhost:9200/test?pretty' -d @config/elastic_mapping.json
script:
  - coverage run --source='.' manage.py test
after_success:
  coveralls
branches:
  only:
    - master
    - dev
