language: python
python:
  - "3.5"
env:
  - ORACLE_HOME=/home/travis/oracle/
  - LD_LIBRARY_PATH=/home/travis/oracle/
  - DYLD_LIBRARY_PATH=/home/travis/oracle/
before_install:
  - "wget https://www.ebi.ac.uk/~luciani/Oracle/oracle.zip && unzip oracle.zip"
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - sleep 3
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source='.' manage.py test
after_success:
  coveralls
