sudo: required
dist: trusty
language: python
python:
  - "3.5"
addons:
  chrome: stable
before_install:
  - jdk_switcher use oraclejdk8
  - "wget https://www.ebi.ac.uk/~luciani/Oracle/oracle.zip && unzip oracle.zip -d oracle"
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "export ORACLE_HOME=$(pwd)/oracle/"
  - "export LD_LIBRARY_PATH=$(pwd)/oracle/"
  - "export DYLD_LIBRARY_PATH=$(pwd)/oracle/"
  - "export BROWSER_TEST=chrome"
  - wget http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo cp chromedriver /usr/local/bin/.
  - sleep 3
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.1.deb && sudo dpkg -i --force-confnew elasticsearch-5.1.1.deb && sudo service elasticsearch restart
services:
  - elasticsearch
install:
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt
  - pip install tblib
before_script:
  - sleep 10
  - curl -XPUT 'localhost:9200/test?pretty' -d @config/elastic_mapping.json
script:
  - coverage run --source='.' manage.py test
after_success:
  coveralls
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      - protein-families-team:z1Fwm5IHFOou6YBDj0fRcTTY#interpro7
branches:
  only:
    - master
    - dev
    - django2
