language: python
python:
  - "3.5"
before_install:
  - "wget https://www.ebi.ac.uk/~luciani/Oracle/oracle.zip && unzip oracle.zip -d oracle"
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "export ORACLE_HOME=$(pwd)/oracle/"
  - "export LD_LIBRARY_PATH=$(pwd)/oracle/"
  - "export DYLD_LIBRARY_PATH=$(pwd)/oracle/"
  - sleep 3
install:
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt
before_script:
  - curl -sSL https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=5.5.3 SOLR_COLLECTION=test SOLR_COLLECTION_CONF=config/solr/ bash
script:
  - coverage run --source='.' manage.py test
after_success:
  coveralls
branches:
  only:
    - master
    - new_datawarehouse
    - solr_exploration
