sudo: required
dist: xenial
services:
  - xvfb
language: python
python:
  - "3.6"
addons:
  chrome: stable
before_install:
  - "export BROWSER_TEST=chrome"
  - wget http://chromedriver.storage.googleapis.com/81.0.4044.69/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo cp chromedriver /usr/local/bin/. && sudo chmod 755 /usr/local/bin/chromedriver
  - sleep 3
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.3.0-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.3.0-amd64.deb
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo service elasticsearch restart
install:
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt
  - pip install tblib
  - pip freeze
before_script:
  - sleep 10
  - "curl 'localhost:9200'"
  - "curl -XPUT 'localhost:9200/test?pretty' -H 'Content-Type: application/json' -d @config/elastic_mapping.json"
  - "curl -XPUT 'localhost:9200/ida?pretty' -H 'Content-Type: application/json' -d @config/elastic_ida_mapping.json"
script:
  - coverage run --source='.' manage.py test
after_success:
  coveralls
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: VK+fSEw/3kwgxXiBLnuKdLb7pHl5oB5PqvZYZATW5uCHOuBr6z++10wVatuK0LYMRT3582v+0PJ+Vu59Wgj/iYn+l8VR24QzyKQsHfHBrt+gWlOWHhKkVlfBwKnoPaLGyw90epWRYRWKRkBJFbMROWcWxxxk5KeflPgc1gT5Qd69BiZWgrffAKfNHRr7aqA52B0lrg2H8hRY1fUrUfWh3Ns3PePrFTLxim4efB84ITuXpEn+H8M+J6EHk+NBRanPuNa0fln49PHJMsTxwkIOEZXGkha/PpKOVxnifvq05Qyb17+x54PuoLktqkok392PG9+O1nW9E4tcWQVtYKtkr29NR2K+dHZX3rZoS21GuMqxl8ZuP2wwaJqP48zu2QGCFk03LjWg/NgdBV+TBUG43imdKS8cvVPWSRh6IRFPbDwCGcUVMe0qwo+nYaGkj9BL28/YKkcMFBSU9SfuUt2/+6kvsXHPRKHJ9BO5ZuK+UEbVqID8ijmplrMzHo6lyWgciBsC0j81e5Rg0kuE6LpR9fzP35bQQIHZFJWDJHKkuDqJhivI2LXQy3wEe7HRr1WKfmNvf5MXDKFrftl2axydxYRVrCm5OIcdA6XJGKmOqGTtrDuGPpm4Nh7myKo3ftFdp/YjMnPXBezjJUnze6GNi17fRC69DOM2U4gSlJAAczU=
branches:
  only:
    - master
    - dev
    - swagger_update
