hmmer_path: "/Users/gsalazar/Downloads/hmmer-3.1b2-macosx-intel/binaries/"
tmp_path: "/tmp/"
django_cors: true
solr_test: "http://localhost:9200/test/relationship"

members:
  gene3d:
    filter: "gene3d"
    label: "Gene3D"
    accession: 'G3DSA:[0-9]{1}\.[0-9]{2,3}\.[0-9]{1,4}\.[0-9]{2,4}$'
    options: []
    options_per_family: []
  hamap:
    filter: "hamap"
    label: "HAMAP"
    accession: 'MF_[0-9]{5}(_(A|B){1})?$'
    options: []
    options_per_family: []
  panther:
    filter: "panther"
    label: "PANTHER"
    accession: 'PTHR[0-9]{5}(:SF[0-9]{1,3})?$'
    options: []
    options_per_family: []
  pirsf:
    filter: "pirsf"
    label: "PIRSF"
    accession: 'PIRSF[0-9]{6}$'
    options: []
    options_per_family: []
  prints:
    filter: "prints"
    label: "PRINTS"
    accession: 'PR[0-9]{5}$'
    options: []
    options_per_family: []
  prosite:
    filter: "prosite"
    label: "PROSITE patterns"
    accession: 'PS[0-9]{5}$'
    options: []
    options_per_family: []
  prosite_profiles:
    filter: "prosite_profiles"
    label: "PROSITE profiles"
    accession: 'PS[0-9]{5}$'
    options: []
    options_per_family: []
  pfam:
    filter: "pfam"
    label: "Pfam"
    accession: 'PF[0-9]{5}$'
    options:
      -
        label: "Clans"
        filter: "clans"
    options_per_family:
      -
        label: "Active Sites"
        filter: "active_sites"
  prodom:
    filter: "prodom"
    label: "ProDom"
    accession: 'PD[A-Z0-9]{6}$'
    options: []
    options_per_family: []
  smart:
    filter: "smart"
    label: "SMART"
    accession: 'SM[0-9]{5}$'
    options: []
    options_per_family: []
  ssf:
    filter: "ssf"
    label: "SUPERFAMILY"
    accession: 'SSF[0-9]{5,6}$'
    options: []
    options_per_family: []
  tigrfams:
    filter: "tigrfams"
    label: "TIGRFAMs"
    accession: 'TIGR[0-9]{5}$'
    options: []
    options_per_family: []
  cdd:
    filter: "cdd"
    label: "CDD"
    accession: '(?:c|s)d[0-9]{5}$'
    options: []
    options_per_family: []
