hmmer_path: "/tmp/hmmer-3.1b2-macosx-intel/binaries/"
tmp_path: "/tmp/"
django_cors: true
searcher_path: "http://hmmer-prod-db01:9200"
searcher_index: "current"
searcher_ida_index: "ida"
searcher_test_path: "http://localhost:9200"
api_url: "http://localhost:8007/api/"
url_path_prefix: ""
use_test_db: false
enable_caching: false
enable_cache_write: false
redis: "redis://127.0.0.1:6379/1"
query_timeout: 60
cache_volatile_key_ttl: 3600
default_page_size: 20
debug: true
allowed_host: []
static_url: "/interpro7/api/static_files/"
hmmerweb: 'https://www.ebi.ac.uk/Tools/hmmer/search/hmmscan'
sendmail_path: "/usr/sbin/sendmail"
http_proxy: ""

members:
  cathgene3d:
    filter: "cathgene3d"
    label: "Cath gene3d"
    accession: 'G3DSA:[0-9]{1}\.[0-9]{2,3}\.[0-9]{1,4}\.[0-9]{2,5}$'
    options: []
    options_per_family: []
  hamap:
    filter: "hamap"
    label: "HAMAP"
    accession: 'MF_[0-9]{5}(_(A|B){1})?$'
    options: []
    options_per_family: []
  panther:
    filter: "panther"
    label: "PANTHER"
    accession: 'PTHR[0-9]{5}(:SF[0-9]{1,3})?$'
    options: []
    options_per_family: []
  pirsf:
    filter: "pirsf"
    label: "PIRSF"
    accession: 'PIRSF[0-9]{6}$'
    options: []
    options_per_family: []
  prints:
    filter: "prints"
    label: "PRINTS"
    accession: 'PR[0-9]{5}$'
    options: []
    options_per_family: []
  prosite:
    filter: "prosite"
    label: "PROSITE patterns"
    accession: 'PS[0-9]{5}$'
    options: []
    options_per_family: []
  profile:
    filter: "profile"
    label: "PROSITE profiles"
    accession: 'PS[0-9]{5}$'
    options: []
    options_per_family: []
  pfam:
    filter: "pfam"
    label: "Pfam"
    accession: 'PF[0-9]{5}$'
    options:
      -
        label: "Clans"
        filter: "clans"
    options_per_family:
      -
        label: "Active Sites"
        filter: "active_sites"
  smart:
    filter: "smart"
    label: "SMART"
    accession: 'SM[0-9]{5}$'
    options: []
    options_per_family: []
  ssf:
    filter: "ssf"
    label: "SUPERFAMILY"
    accession: 'SSF[0-9]{5,6}$'
    options: []
    options_per_family: []
  tigrfams:
    filter: "tigrfams"
    label: "TIGRFAMs"
    accession: 'TIGR[0-9]{5}$'
    options: []
    options_per_family: []
  ncbifam:
    filter: "ncbifam"
    label: "NCBIfam"
    accession: '(TIGR[0-9]{5})|(NF[0-9]{6})$'
    options: []
    options_per_family: []
  cdd:
    filter: "cdd"
    label: "CDD"
    accession: '(?:c|s)d[0-9]{5}$'
    options: []
    options_per_family: []
  mobidblt:
    filter: "mobidblt"
    label: "mobidblt"
    accession: 'mobidb-lite'
    options: []
    options_per_family: []
  sfld:
    filter: "sfld"
    label: "sfld"
    accession: 'SFLD[FGS][0-9]{5}$'
    options: []
    options_per_family: []
  funfam:
    filter: "funfam"
    label: "funfam"
    accession: 'G3DSA:[0-9]{1}\.[0-9]{2,3}\.[0-9]{1,4}\.[0-9]{2,5}:.+'
    options: []
    options_per_family: []
  antifam:
    filter: "antifam"
    label: "AntiFam"
    accession: 'ANF[0-9]{5}'
    options: []
    options_per_family: []

cross_references:
    'EC':
        'rank': 19
        'description': 'ENZYME is a repository of information relative to the nomenclature of enzymes. It is primarily based on the recommendations of the Nomenclature Committee of the International Union of Biochemistry and Molecular Biology (IUBMB) and it describes each type of characterized enzyme for which an EC (Enzyme Commission) number has been provided.'
        'urlPattern': 'http://www.ebi.ac.uk/intenz/query?cmd=SearchEC&ec={accession}'
    'COME':
        'displayName': 'COMe'
        'rank': 27
        'description': 'COMe is an attempt to classify metalloproteins and some other complex proteins using the concept of bioinorganic motif (a common structural feature of a class of functionally related, but not necessarily homologous, proteins, that includes the metal atom(s) and first coordination shell ligands).'
        'urlPattern': 'http://www.flymine.org/come/entry?gn={accession}'
    'IUPHAR':
        'displayName': 'IUPHAR receptor code'
        'rank': 22
        'description': 'The IUPHAR database incorporates detailed pharmacological, functional and pathophysiological information on G Protein-Coupled Receptors, Voltage-Gated Ion Channels, Ligand-Gated Ion Channels and Nuclear Hormone Receptors.'
        'urlPattern': 'https://www.guidetopharmacology.org/GRAC/ObjectDisplayForward?objectId={accession}'
    'CAZY':
        'displayName': 'CAZy'
        'rank': 20
        'urlPattern': 'http://www.cazy.org/{ACCESSION}.html'
    'CATH':
        'rank': 25
        'urlPattern': 'http://www.cathdb.info/version/latest/superfamily/{accession}'
        'description': 'CATH is a classification of protein structures downloaded from the Protein Data Bank.'
    'PROSITEDOC':
        'rank': 18
        'description': 'PROSITE is a database of protein families and domains.'
        'urlPattern': 'http://prosite.expasy.org/{accession}'
    'PRIAM':
        'rank': 38
        'description': "ENZYME-SPECIFIC PROFILES for metabolic pathway prediction."
        'urlPattern': 'http://priam.prabi.fr/cgi-bin/ReqPRIAM_png.pl?priam_ac={accession}'
    'SCOP':
        'rank': 24
        'urlPattern': 'http://scop.berkeley.edu/search/?key={accession}'
        'description': 'The SCOP database, created by manual inspection and abetted by a battery of automated methods, aims to provide a detailed and comprehensive description of the structural and evolutionary relationships between all proteins whose structure is known.'
    'MODBASE':
        'rank': 32
    'SFLD':
        'rank': 16
    'PANDIT':
        'displayName': 'PANDIT'
        'rank': 28
        'description': 'The Protein and Associated NucleotideDomains with Inferred Trees (PANDIT) database is a collection of multiple sequence alignments and phylogenetic trees covering many common protein domains.'
        'urlPattern': 'http://www.ebi.ac.uk/goldman-srv/pandit/pandit.cgi?action=browse&fam={accession}'
    'MSDSITE':
        'displayName': 'PDBeMotif'
        'rank': 29
        'description': 'PDBeMotif is an extremely fast and powerful search tool that facilitates exploration of the Protein Data Bank (PDB) by combining protein sequence, chemical structure and 3D data in a single search.'
        'urlPattern': 'http://www.ebi.ac.uk/pdbe-site/pdbemotif/barChartPattern?pattern1={accession}'
    'PRINTS':
        'rank': 4
    'GO CLASSIFICATION':
        'displayName': 'GO Classification'
        'rank': 15
    'PFAM':
        'displayName': 'Pfam'
        'rank': 2
    'INTERPRO':
        'displayName': 'InterPro'
        'rank': 14
    'CDD':
        'rank': 43
    'BLOCKS':
        'displayName': 'Blocks'
        'rank': 17
    'PROSITE PROFILES':
        'displayName': 'PROSITE profiles'
        'rank': 7
    'TIGRFAMS':
        'rank': 9
    'COG':
        'rank': 23
    'PROSITE PATTERNS':
        'displayName': 'PROSITE patterns'
        'rank': 6
    'HAMAP':
        'rank': 36
    'SMART':
        'rank': 8
    'UNIPROTKB/SWISS-PROT':
        'displayName': 'UniProtKB/Swiss-Prot'
        'rank': 12
    'UNIPROTKB/TREMBL':
        'displayName': 'UniProtKB/TrEMBL'
        'rank': 13
    'PIRSF':
        'rank': 3
    'PANTHER':
        'rank': 1
    'SWISS-MODEL':
        'rank': 30
    'CATHGENE3D':
        'rank': 10
    'SUPERFAMILY':
        'rank': 11
    'IUPHAR RECEPTOR CODE':
        'displayName': 'IUPHAR receptor code'
        'rank': 22
        'description': 'The IUPHAR database incorporates detailed pharmacological, functional and pathophysiological information on G Protein-Coupled Receptors, Voltage-Gated Ion Channels, Ligand-Gated Ion Channels and Nuclear Hormone Receptors.'
        'urlPattern': 'https://www.guidetopharmacology.org/GRAC/ObjectDisplayForward?objectId={accession}'
    'ADAN':
        'rank': 33
    'PDB':
        'rank': 26
    'DBD':
        'rank': 34
    'ENZYME':
        'rank': 19
        'description': 'ENZYME is a repository of information relative to the nomenclature of enzymes. It is primarily based on the recommendations of the Nomenclature Committee of the International Union of Biochemistry and Molecular Biology (IUBMB) and it describes each type of characterized enzyme for which an EC (Enzyme Commission) number has been provided.'
        'urlPattern': 'http://www.ebi.ac.uk/intenz/query?cmd=SearchEC&ec={accession}'
    'MOBIDB LITE':
        'rank': 44
    'KEGG':
        'rank': 39
    'PFAMCLAN':
        'displayName': 'PfamClan'
        'rank': 97
    'MEROPS':
        'rank': 21
    'OMIM':
        'rank': 31
    'REACTOME':
        'displayName': 'Reactome'
        'rank': 42
    'METACYC':
        'displayName': 'MetaCyc'
        'rank': 41
    'UNIPROT':
        'displayName': 'UniProt'
        'rank': 35
    'UNIPATHWAY':
        'displayName': 'UniPathway'
        'rank': 40

sets:
  'pfam':
    accession: 'CL\d{4}'
  'cdd':
    accession: 'cl\d{5}'
  'pirsf':
    accession: '[Pp][Ii][Rr][Ss][Ff][0-9]{6}'
  'panther':
    accession: 'PTHR[0-9]{5}(:SF[0-9]{1,3})?'

key_organisms:
  '39947': 'Oryza sativa subsp. japonica'
  '3702': 'Arabidopsis thaliana'
  '9606': 'Homo sapiens'
  '7955': 'Danio rerio'
  '10090': 'Mus musculus'
  '7227': 'Drosophila melanogaster'
  '6239': 'Caenorhabditis elegans'
  '559292': 'Saccharomyces cerevisiae'
  '284812': 'Schizosaccharomyces pombe'
  '83333': 'Escherichia coli'
  '10665': 'Escherichia virus T4'
  '2242': 'Halobacterium salinarum'

key_go_terms:
  'GO:0003824': 'Catalytic activity'
  'GO:0003677': 'DNA binding'
  'GO:0008152': 'Metabolic process'
  'GO:0055114': 'Oxidation-reduction process'
  'GO:0019867': 'Outer membrane'
  'GO:0005524': 'ATP binding'
  'GO:0016491': 'Oxidoreductase activity'
  'GO:0006810': 'Transport'
  'GO:0006260': 'DNA replication'
  'GO:0016021': 'Integral component of membrane'
  'GO:0048037': 'Cofactor bindind'
  'GO:0042575': 'DNA polymerase complex'
  'GO:0030031': 'Cell projection assembly'
  'GO:0016043': 'Cellular component organization'
  'GO:0016049': 'Cell growth'
