# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-22 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('entry_id', models.CharField(max_length=10, null=True)),
                ('accession', models.CharField(max_length=19, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=14)),
                ('name', models.TextField()),
                ('short_name', models.CharField(max_length=30)),
                ('other_names', jsonfield.fields.JSONField()),
                ('source_database', models.CharField(db_index=True, max_length=20)),
                ('member_databases', jsonfield.fields.JSONField()),
                ('go_terms', jsonfield.fields.JSONField()),
                ('description', jsonfield.fields.JSONField()),
                ('wikipedia', models.TextField(null=True)),
                ('literature', jsonfield.fields.JSONField()),
                ('integrated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webfront.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('accession', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=20, unique=True)),
                ('organism', jsonfield.fields.JSONField()),
                ('name', models.CharField(max_length=20)),
                ('short_name', models.CharField(max_length=20, null=True)),
                ('other_names', jsonfield.fields.JSONField()),
                ('description', jsonfield.fields.JSONField()),
                ('sequence', models.TextField()),
                ('length', models.IntegerField()),
                ('proteome', models.CharField(max_length=20)),
                ('gene', models.CharField(max_length=20)),
                ('go_terms', jsonfield.fields.JSONField()),
                ('evidence_code', models.IntegerField()),
                ('feature', jsonfield.fields.JSONField()),
                ('genomic_context', jsonfield.fields.JSONField()),
                ('source_database', models.CharField(db_index=True, default='uniprot', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('accession', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('short_name', models.CharField(max_length=20, null=True)),
                ('other_names', jsonfield.fields.JSONField()),
                ('experiment_type', models.CharField(max_length=30)),
                ('release_date', models.DateField()),
                ('authors', jsonfield.fields.JSONField()),
                ('chains', jsonfield.fields.JSONField()),
                ('source_database', models.CharField(db_index=True, default='pdb', max_length=20)),
            ],
        ),
    ]
