# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('entry_id', models.CharField(max_length=10, null=True)),
                ('accession', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('name', models.TextField()),
                ('short_name', models.CharField(max_length=100)),
                ('source_database', models.CharField(db_index=True, max_length=100)),
                ('member_databases', jsonfield.fields.JSONField(null=True)),
                ('go_terms', jsonfield.fields.JSONField(null=True)),
                ('description', jsonfield.fields.JSONField(null=True)),
                ('wikipedia', models.TextField(null=True)),
                ('literature', jsonfield.fields.JSONField(null=True)),
                ('hierarchy', jsonfield.fields.JSONField(null=True)),
                ('cross_references', jsonfield.fields.JSONField(null=True)),
                ('entry_date', models.DateField(null=True)),
                ('is_featured', models.CharField(max_length=2)),
                ('integrated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webfront.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='EntryAnnotation',
            fields=[
                ('annotation_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32)),
                ('value', models.BinaryField()),
                ('mime_type', models.CharField(max_length=32)),
                ('accession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webfront.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('accession', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=16, unique=True)),
                ('organism', jsonfield.fields.JSONField(null=True)),
                ('name', models.CharField(max_length=20)),
                ('other_names', jsonfield.fields.JSONField(null=True)),
                ('sequence', models.TextField()),
                ('length', models.IntegerField()),
                ('proteomes', jsonfield.fields.JSONField(null=True)),
                ('gene', models.CharField(max_length=70, null=True)),
                ('go_terms', jsonfield.fields.JSONField(null=True)),
                ('evidence_code', models.IntegerField()),
                ('source_database', models.CharField(db_index=True, default='unreviewed', max_length=20)),
                ('residues', jsonfield.fields.JSONField(null=True)),
                ('structure', jsonfield.fields.JSONField(default={})),
                ('fragment', models.CharField(max_length=1)),
                ('tax_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Proteome',
            fields=[
                ('accession', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('is_reference', models.CharField(max_length=1)),
                ('strain', models.CharField(max_length=512)),
                ('assembly', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('accession', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('source_database', models.CharField(db_index=True, max_length=20)),
                ('integrated', jsonfield.fields.JSONField(null=True)),
                ('relationships', jsonfield.fields.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('accession', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('short_name', models.CharField(max_length=20, null=True)),
                ('other_names', jsonfield.fields.JSONField(null=True)),
                ('experiment_type', models.CharField(max_length=16)),
                ('release_date', models.DateField()),
                ('literature', jsonfield.fields.JSONField(null=True)),
                ('chains', jsonfield.fields.JSONField(null=True)),
                ('source_database', models.CharField(db_index=True, default='pdb', max_length=10)),
                ('resolution', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('accession', models.IntegerField(primary_key=True, serialize=False)),
                ('scientific_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=512)),
                ('lineage', models.CharField(max_length=512)),
                ('rank', models.CharField(max_length=20)),
                ('children', jsonfield.fields.JSONField(null=True)),
                ('left_number', models.IntegerField()),
                ('right_number', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webfront.Taxonomy')),
            ],
        ),
        migrations.AddField(
            model_name='proteome',
            name='taxonomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webfront.Taxonomy'),
        ),
    ]
