# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-05 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0001_unified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='fragment',
        ),
        migrations.AddField(
            model_name='database',
            name='prev_release_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='prev_version',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='overlap_with',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='protein',
            name='is_fragment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='set',
            name='is_set',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proteome',
            name='is_reference',
            field=models.BooleanField(default=False),
        ),
    ]
