# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 10:19
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0001_model_from_new_dw'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='description',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
