# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-14 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0001_basic_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='domain_architectures',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='protein',
            name='domain_architectures',
            field=models.TextField(null=True),
        ),
    ]
