# Generated by Django 2.0.4 on 2018-05-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='code',
        ),
    ]
