# Generated by Django 2.1.10 on 2019-10-15 10:52

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("webfront", "0001_merged")]

    operations = [
        migrations.CreateModel(
            name="TaxonomyPerEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("counts", jsonfield.fields.JSONField(null=True)),
                (
                    "entry_acc",
                    models.ForeignKey(
                        db_column="entry_acc",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="webfront.Entry",
                    ),
                ),
                (
                    "taxonomy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="webfront.Taxonomy",
                    ),
                ),
            ],
        )
    ]
