# Generated by Django 2.1.4 on 2018-12-21 11:27

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0001_merged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignments', jsonfield.fields.JSONField(null=True)),
                ('entry_acc', models.ForeignKey(db_column='entry_acc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webfront.Entry')),
                ('set_acc', models.ForeignKey(db_column='set_acc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webfront.Set')),
            ],
        ),
    ]
