# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-19 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0002_entry_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='fragment',
            field=models.CharField(default='N', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protein',
            name='residues',
            field=jsonfield.fields.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
