# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0002_removing_db_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
