# Generated by Django 2.1.7 on 2019-04-30 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("webfront", "0002_alignments")]

    operations = [
        migrations.RenameField(
            model_name="alignment", old_name="alignments", new_name="domains"
        ),
        migrations.AddField(
            model_name="alignment", name="score", field=models.FloatField(null=True)
        ),
        migrations.AddField(
            model_name="alignment",
            name="seq_length",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="alignment",
            name="target_acc",
            field=models.ForeignKey(
                db_column="target_acc",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="target_acc",
                to="webfront.Entry",
            ),
        ),
        migrations.AddField(
            model_name="alignment",
            name="target_set_acc",
            field=models.ForeignKey(
                db_column="target_set_acc",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="target_set_acc",
                to="webfront.Set",
            ),
        ),
    ]
