# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-05 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0002_enum_as_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='tax_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='accession',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
