# Generated by Django 2.1.7 on 2019-05-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("webfront", "0003_alignment_changes")]

    operations = [
        migrations.AddField(
            model_name="protein", name="ida", field=models.TextField(null=True)
        ),
        migrations.AddField(
            model_name="protein",
            name="ida_id",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
