# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-13 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0003_taxonomy_str'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='overlap_with',
            new_name='overlaps_with',
        ),
    ]
