# Generated by Django 2.1.10 on 2019-10-25 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("webfront", "0003_taxonomy_per_entryDB")]

    operations = [
        migrations.RenameField(
            model_name="taxonomyperentrydb",
            old_name="entry_db",
            new_name="source_database",
        ),
        migrations.AlterField(
            model_name="taxonomyperentry",
            name="taxonomy",
            field=models.ForeignKey(
                blank=True,
                db_column="tax_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="webfront.Taxonomy",
            ),
        ),
        migrations.AlterField(
            model_name="taxonomyperentrydb",
            name="taxonomy",
            field=models.ForeignKey(
                blank=True,
                db_column="tax_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="webfront.Taxonomy",
            ),
        ),
    ]
