# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-12 09:53
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0003_protein_residues'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='structure',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
