# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-12 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0004_structure_info_for_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='tax_id',
            field=models.IntegerField(default=0),
        ),
    ]
