# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-15 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0004_overlapS'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='prev_release_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
