# Generated by Django 3.0.1 on 2020-01-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("webfront", "0004_taxonomy_per_entryX")]

    operations = [
        migrations.RemoveField(model_name="protein", name="other_names"),
        migrations.RemoveField(model_name="protein", name="size"),
    ]
