# Generated by Django 2.0.9 on 2018-10-24 13:52

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0005_timezones'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='extra_features',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
