# Generated by Django 3.0.1 on 2020-02-04 15:33

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("webfront", "0005_droping_columns")]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="interactions",
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="entry",
            name="pathways",
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
