# Generated by Django 2.0.9 on 2018-10-02 14:32

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0005_timezones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release_Note',
            fields=[
                ('version', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('release_date', models.DateTimeField(null=True)),
                ('content', jsonfield.fields.JSONField(null=True)),
            ],
        ),
    ]
