# Generated by Django 2.1.9 on 2019-06-21 15:53

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("webfront", "0005_isoforms")]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="secondary_structures",
            field=jsonfield.fields.JSONField(null=True),
        )
    ]
