# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-29 15:20
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0005_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='cross_references',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
    ]
