# Generated by Django 2.1.10 on 2019-08-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("webfront", "0006_secondary")]

    operations = [
        migrations.AlterModelOptions(
            name="alignment", options={"ordering": ["set_acc", "entry_acc"]}
        )
    ]
