# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0006_entry_cross_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryAnnotation',
            fields=[
                ('annotation_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('value', models.BinaryField()),
                ('mime_type', models.CharField(max_length=64)),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webfront.Entry')),
            ],
        ),
    ]
