# Generated by Django 3.0.1 on 2020-02-06 09:27

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("webfront", "0006_interaction_and_pathways")]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="history",
            field=jsonfield.fields.JSONField(null=True),
        )
    ]
