# Generated by Django 2.0.9 on 2018-10-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0006_extra_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='deletion_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='is_alive',
            field=models.BooleanField(default=False),
        ),
    ]
