# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-25 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0006_entry_cross_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('accession', models.IntegerField(primary_key=True, serialize=False)),
                ('scientific_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=512)),
                ('lineage', models.CharField(max_length=512)),
                ('rank', models.CharField(max_length=20)),
                ('children', jsonfield.fields.JSONField()),
                ('left', models.IntegerField()),
                ('right', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webfront.Taxonomy')),
            ],
        ),
    ]
