# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-28 15:45
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0007_adding_taxonomy_proteome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='proteome',
        ),
        migrations.AddField(
            model_name='protein',
            name='proteomes',
            field=jsonfield.fields.JSONField(default='[]'),
            preserve_default=False,
        ),
    ]
