# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-25 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0007_adding_taxonomy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proteome',
            fields=[
                ('accession', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('is_reference', models.BooleanField()),
                ('number_of_proteins', models.IntegerField()),
                ('strain', models.CharField(max_length=512)),
                ('assembly', models.CharField(max_length=512)),
                ('taxonomy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webfront.Taxonomy')),
            ],
        ),
    ]
