# Generated by Django 2.0.9 on 2018-10-26 10:06

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0007_is_alive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='proteomes',
        ),
        migrations.AddField(
            model_name='protein',
            name='counts',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='protein',
            name='proteome',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
