# Generated by Django 3.0.1 on 2020-04-09 15:04

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("webfront", "0007_history")]

    operations = [
        migrations.RemoveField(model_name="set", name="integrated"),
        migrations.RemoveField(model_name="set", name="is_set"),
        migrations.RemoveField(model_name="structure", name="other_names"),
        migrations.RemoveField(model_name="structure", name="short_name"),
        migrations.AlterField(
            model_name="protein",
            name="structure",
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
    ]
