# Generated by Django 3.0.7 on 2020-06-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("webfront", "0008_dw_changes")]

    operations = [
        migrations.AddField(
            model_name="entryannotation",
            name="num_sequnces",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="entryannotation",
            name="accession",
            field=models.ForeignKey(
                db_column="accession",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="webfront.Entry",
            ),
        ),
    ]
