# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0007_entryannotation'),
        ('webfront', '0008_proteome_to_proteomes'),
    ]

    operations = [
    ]
