# Generated by Django 3.0.7 on 2020-08-24 13:42

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("webfront", "0009_entry_annotation_changes")]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="details",
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="set",
            name="authors",
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="set",
            name="literature",
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
