# Generated by Django 2.1.10 on 2020-08-10 09:32

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("webfront", "0009_entry_annotation_changes")]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="wikipedia",
            field=jsonfield.fields.JSONField(null=True),
        )
    ]
