# Generated by Django 2.0.9 on 2018-10-29 14:14

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0009_set_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='counts',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
