# Generated by Django 2.0.9 on 2018-10-29 15:34

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0010_tax_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteome',
            name='counts',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
