# Generated by Django 2.0.9 on 2018-10-29 17:09

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0011_proteome_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='counts',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
