# Generated by Django 3.0.7 on 2021-01-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("webfront", "0011_pfam2interpro")]

    operations = [
        migrations.RemoveField(model_name="protein", name="extra_features"),
        migrations.RemoveField(model_name="protein", name="residues"),
        migrations.RemoveField(model_name="protein", name="sequence"),
        migrations.AddField(
            model_name="protein",
            name="sequence_bin",
            field=models.BinaryField(db_column="sequence", null=True),
        ),
    ]
