# Generated by Django 3.0.7 on 2021-01-11 16:29

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("webfront", "0012_seq_and_seq_raw")]

    operations = [
        migrations.CreateModel(
            name="ProteinExtraFeatures",
            fields=[
                ("feature_id", models.IntegerField(primary_key=True, serialize=False)),
                ("protein_acc", models.CharField(max_length=15)),
                ("entry_acc", models.CharField(max_length=25)),
                ("source_database", models.CharField(max_length=10)),
                ("location_start", models.IntegerField()),
                ("location_end", models.IntegerField()),
                ("sequence_feature", models.CharField(max_length=35)),
            ],
            options={"db_table": "webfront_proteinfeature"},
        ),
        migrations.CreateModel(
            name="ProteinResidues",
            fields=[
                ("residue_id", models.IntegerField(primary_key=True, serialize=False)),
                ("protein_acc", models.CharField(max_length=15)),
                ("entry_acc", models.CharField(max_length=25)),
                ("entry_name", models.CharField(max_length=100)),
                ("source_database", models.CharField(max_length=10)),
                ("description", models.CharField(max_length=255)),
                ("fragments", jsonfield.fields.JSONField(null=True)),
            ],
            options={"db_table": "webfront_proteinresidue"},
        ),
    ]
