# Generated by Django 3.0.7 on 2021-02-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("webfront", "0014_structural_model")]

    operations = [
        migrations.AddField(
            model_name="structuralmodel",
            name="lddt",
            field=models.FloatField(default=0),
            preserve_default=False,
        )
    ]
