# Generated by Django 3.0.7 on 2021-10-15 15:48

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("webfront", "0016_structural_model_algorithm")]

    operations = [
        migrations.AddField(
            model_name="entry", name="taxa", field=jsonfield.fields.JSONField(null=True)
        )
    ]
