# Generated by Django 3.1.7 on 2021-11-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0017_taxa_modifier'),
        ('webfront', '0017_structural_model_plddt'),
    ]

    operations = [
    ]
