# Generated by Django 3.2.8 on 2022-02-01 12:14

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0017_structural_model_plddt'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='taxa',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
