# Generated by Django 3.2.8 on 2022-03-16 13:29

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0018_taxa_modifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='taxa',
        ),
        migrations.CreateModel(
            name='EntryTaxa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa', jsonfield.fields.JSONField(null=True)),
                ('accession', models.OneToOneField(db_column='accession', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webfront.entry')),
            ],
            options={
                'db_table': 'webfront_entrytaxa',
            },
        ),
    ]
