# Generated by Django 3.2.12 on 2022-08-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("webfront", "0019_entrytaxa_table")]

    operations = [
        migrations.AlterField(
            model_name="entryannotation",
            name="num_sequences",
            field=models.IntegerField(null=True),
        )
    ]
