# Generated by Django 3.2.15 on 2023-01-03 14:29

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("webfront", "0020_alter_entryannotation_num_sequences")]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="set_info",
            field=jsonfield.fields.JSONField(null=True),
        )
    ]
