# Generated by Django 3.2.15 on 2023-08-03 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webfront", "0021_set_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChainSequence",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("chain", models.CharField(db_column="chain_acc", max_length=10)),
                ("sequence_bin", models.BinaryField(db_column="sequence", null=True)),
                ("length", models.IntegerField()),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        db_column="structure_acc",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="webfront.structure",
                    ),
                ),
            ],
            options={
                "db_table": "webfront_chain_sequence",
            },
        ),
    ]
