# Generated by Django 3.2.20 on 2023-09-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0022_chain_sequence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='is_alive',
            new_name='is_public',
        ),
    ]
