# Generated by Django 3.2.19 on 2023-10-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webfront", "0023_rename_is_alive_entry_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="llm_description",
            field=models.TextField(null=True),
        ),
    ]
