# Generated by Django 3.2.15 on 2023-11-09 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webfront", "0024_entry_llm_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Alignment",
        ),
    ]
