# Generated by Django 3.2.15 on 2023-11-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webfront", "0025_remove_set_alignment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StructuralModel",
        ),
    ]
