# Generated by Django 3.2.15 on 2023-12-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0026_remove_structuralmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='llm_description',
        ),
    ]
