# Generated by Django 3.2.23 on 2024-02-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0027_remove_llm_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='in_alphafold',
            field=models.BooleanField(default=False),
        ),
    ]
