# Generated by Django 3.2.23 on 2024-02-21 10:18

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0028_in_alphafold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='entry',
            name='is_llm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='is_reviewed_llm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='representative_structure',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
