# Generated by Django 3.2.24 on 2024-03-13 13:38

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0029_remove_is_featured_plus_llm_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteomePerEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', jsonfield.fields.JSONField(null=True)),
                ('num_proteins', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProteomePerEntryDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_database', models.CharField(db_index=True, max_length=100)),
                ('counts', jsonfield.fields.JSONField(null=True)),
                ('num_proteins', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='proteome',
            name='num_proteins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='num_proteins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taxonomyperentry',
            name='num_proteins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taxonomyperentrydb',
            name='num_proteins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='taxonomyperentry',
            index=models.Index(fields=['entry_acc', 'taxonomy'], name='webfront_ta_entry_a_9b7542_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomyperentrydb',
            index=models.Index(fields=['source_database', 'taxonomy'], name='webfront_ta_source__af48cb_idx'),
        ),
        migrations.AddField(
            model_name='proteomeperentrydb',
            name='proteome',
            field=models.ForeignKey(blank=True, db_column='accession', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webfront.proteome'),
        ),
        migrations.AddField(
            model_name='proteomeperentry',
            name='entry_acc',
            field=models.ForeignKey(db_column='entry_acc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webfront.entry'),
        ),
        migrations.AddField(
            model_name='proteomeperentry',
            name='proteome',
            field=models.ForeignKey(blank=True, db_column='accession', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webfront.proteome'),
        ),
        migrations.AddIndex(
            model_name='proteomeperentrydb',
            index=models.Index(fields=['source_database', 'proteome'], name='webfront_pr_source__efd3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='proteomeperentry',
            index=models.Index(fields=['entry_acc', 'proteome'], name='webfront_pr_entry_a_5a69ef_idx'),
        ),
    ]
