# Generated by Django 3.2.23 on 2024-05-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0030_num_proteins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteome',
            name='assembly',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='proteome',
            name='strain',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
