# Generated by Django 3.2.23 on 2024-05-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0031_strain_assembly_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_updated_llm',
            field=models.BooleanField(default=False),
        ),
    ]
