# Generated by Django 3.2.24 on 2024-11-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0032_entry_is_updated_llm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteinextrafeatures',
            name='sequence_feature',
            field=models.CharField(max_length=255),
        ),
    ]
