# Generated by Django 4.2.13 on 2025-01-17 10:57

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0033_alter_proteinextrafeatures_sequence_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='wikipedia',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
