# Generated by Django 4.2.19 on 2025-02-24 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webfront", "0034_set_wikipedia"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterProNMatches",
            fields=[
                ("match_id", models.AutoField(primary_key=True, serialize=False)),
                ("in_interpro", models.BooleanField(db_column="in_interpro")),
                ("is_preferred", models.BooleanField(db_column="is_preferred")),
                ("locations", models.JSONField()),
                (
                    "entry",
                    models.ForeignKey(
                        db_column="entry_acc",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="webfront.entry",
                    ),
                ),
                (
                    "protein_acc",
                    models.ForeignKey(
                        db_column="protein_acc",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="webfront.protein",
                    ),
                ),
            ],
            options={
                "db_table": "webfront_interpro_n",
            },
        ),
    ]
