# Generated by Django 4.2.19 on 2025-02-24 14:14

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("webfront", "0035_interpronmatches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="overlaps_with",
            field=jsonfield.fields.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="protein",
            name="structure",
            field=jsonfield.fields.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="set",
            name="authors",
            field=jsonfield.fields.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="set",
            name="literature",
            field=jsonfield.fields.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="set",
            name="wikipedia",
            field=jsonfield.fields.JSONField(default=list),
        ),
    ]
