# Generated by Django 4.2.13 on 2025-03-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0036_default_value_lists_dicts'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='in_bfvd',
            field=models.BooleanField(default=False),
        ),
    ]
