# Generated by Django 4.2.13 on 2025-09-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0037_protein_in_bfvd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='name',
            field=models.CharField(db_collation='case_insensitive', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='accession',
            field=models.CharField(db_collation='case_insensitive', max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.TextField(db_collation='case_insensitive'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='short_name',
            field=models.CharField(db_collation='case_insensitive', max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='source_database',
            field=models.CharField(db_collation='case_insensitive', db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='isoforms',
            name='protein_acc',
            field=models.CharField(db_collation='case_insensitive', max_length=20),
        ),
        migrations.AlterField(
            model_name='protein',
            name='accession',
            field=models.CharField(db_collation='case_insensitive', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='protein',
            name='gene',
            field=models.CharField(db_collation='case_insensitive', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='ida_id',
            field=models.CharField(db_collation='case_insensitive', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='identifier',
            field=models.CharField(db_collation='case_insensitive', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='name',
            field=models.CharField(db_collation='case_insensitive', max_length=20),
        ),
        migrations.AlterField(
            model_name='protein',
            name='proteome',
            field=models.CharField(db_collation='case_insensitive', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='source_database',
            field=models.CharField(db_collation='case_insensitive', db_index=True, default='unreviewed', max_length=20),
        ),
        migrations.AlterField(
            model_name='protein',
            name='tax_id',
            field=models.CharField(db_collation='case_insensitive', default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='proteinextrafeatures',
            name='protein_acc',
            field=models.CharField(db_collation='case_insensitive', max_length=15),
        ),
        migrations.AlterField(
            model_name='proteinresidues',
            name='protein_acc',
            field=models.CharField(db_collation='case_insensitive', max_length=15),
        ),
        migrations.AlterField(
            model_name='proteome',
            name='accession',
            field=models.CharField(db_collation='case_insensitive', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proteomeperentrydb',
            name='source_database',
            field=models.CharField(db_collation='case_insensitive', db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='structure',
            name='accession',
            field=models.CharField(db_collation='case_insensitive', max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='accession',
            field=models.CharField(db_collation='case_insensitive', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxonomyperentrydb',
            name='source_database',
            field=models.CharField(db_collation='case_insensitive', db_index=True, max_length=100),
        ),
    ]
